### ISSUE TITLE
打开提示快捷键错误

### ISSUE THREAD

**Issue by Qwenjin** [s00d/switchshuttle#1]
<img width="260" alt="image" src="https://github.com/user-attachments/assets/462c524d-296e-423a-a8f5-9991f3056800">

软件版本：1.3.5
操作系统：MacOS 12.7.2

如图，但是不影响使用。

**Comment by Qwenjin** [comment]
噢噢 可以在config设置

**Comment by s00d** [comment]
I replaced error messages with notifications in the latest update so that they do not interfere with work. The error indicates that the hotkey is already registered for another command and needs to be changed.

我在最新更新中将错误消息替换为通知，以免干扰工作。错误提示表示该快捷键已被注册为另一命令，需要更改。
